export const CATEGORY_OPTIONS = [
    { label: "스코어", value: "score" },
    { label: "플레이 내용", value: "playContent" },
    { label: "내용 대비 스코어", value: "scoreVsContent" },
    { label: "롱게임 대비 숏게임", value: "longVsShort" },
    { label: "티샷 종합", value: "teeTotal" },
    { label: "티샷 비거리", value: "teeDistance" },
    { label: "티샷 정확도", value: "teeAccuracy" },
    { label: "세컨샷 종합", value: "secondTotal" },
    { label: "180M 이상", value: "dist180Plus" },
    { label: "150-179M", value: "dist150_179" },
    { label: "120-149M", value: "dist120_149" },
    { label: "90-119M", value: "dist90_119" },
    { label: "그린주변샷 종합", value: "greenTotal" },
    { label: "피치샷", value: "pitchShot" },
    { label: "벙커", value: "bunker" },
    { label: "어프로치", value: "approach" },
    { label: "퍼팅 종합", value: "puttingTotal" },
    { label: "9M 이상", value: "putt9Plus" },
    { label: "4-8M", value: "putt4_8" },
    { label: "2-3M", value: "putt2_3" },
    { label: "1M", value: "putt1" },
    { label: "페어웨이 안착률", value: "fairwayHitRate" },
    { label: "그린적중률", value: "girRate" },
    { label: "파세이브률", value: "parSaveRate" },
    { label: "퍼트수", value: "putts" },
    { label: "3퍼트 이상", value: "threePutt" },
    { label: "패널티/OB 수", value: "penaltyOB" },
    { label: "바운스백", value: "bounceBack" },
    { label: "버디 이상 수", value: "birdieOrBetter" },
];

export const BRANCH_OPTIONS = [
    { label: "전체", value: "all" },
    { label: "조이마루점", value: "조이마루점" },
    { label: "구미점", value: "구미점" },
];
