import type { Metadata } from "next";
import "./globals.css";
import { UserActivityTracker } from "@/components/layout/UserActivityTracker";

export const metadata: Metadata = {
  title: "2026 GLA Data Report",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="antialiased"
        suppressHydrationWarning={true}
      >
        {children}
        <UserActivityTracker />
      </body>
    </html>
  );
}