-- Create role_permissions table
CREATE TABLE IF NOT EXISTS public.role_permissions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    menu_key TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('admin', 'coach', 'athlete', 'parent')),
    can_read BOOLEAN NOT NULL DEFAULT false,
    can_write BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    UNIQUE(menu_key, role)
);

-- Enable RLS
ALTER TABLE public.role_permissions ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Enable read access for all users" ON public.role_permissions FOR SELECT USING (true);
-- In a real app, only admins should be able to update/insert, but for now we allow authenticated users for simplicity
CREATE POLICY "Enable insert for authenticated users" ON public.role_permissions FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Enable update for authenticated users" ON public.role_permissions FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Enable delete for authenticated users" ON public.role_permissions FOR DELETE TO authenticated USING (true);

-- Insert default permissions
INSERT INTO public.role_permissions (menu_key, role, can_read, can_write) VALUES
('home', 'admin', true, true),
('home', 'coach', true, true),
('home', 'athlete', true, false),
('home', 'parent', true, false),
('lessons', 'admin', true, true),
('lessons', 'coach', true, true),
('lessons', 'athlete', true, false),
('lessons', 'parent', true, false),
('training', 'admin', true, true),
('training', 'coach', true, true),
('training', 'athlete', true, false),
('training', 'parent', true, false),
('analysis', 'admin', true, true),
('analysis', 'coach', true, true),
('analysis', 'athlete', true, false),
('analysis', 'parent', true, false),
('challenges', 'admin', true, true),
('challenges', 'coach', true, true),
('challenges', 'athlete', true, false),
('challenges', 'parent', true, false),
('tournament-schedule', 'admin', true, true),
('tournament-schedule', 'coach', true, true),
('tournament-schedule', 'athlete', true, false),
('tournament-schedule', 'parent', true, false),
('tournament-results-view', 'admin', true, true),
('tournament-results-view', 'coach', true, true),
('tournament-results-view', 'athlete', true, false),
('tournament-results-view', 'parent', true, false),
('schedule', 'admin', true, true),
('schedule', 'coach', true, true),
('schedule', 'athlete', true, false),
('schedule', 'parent', true, false),
('coach-trip-schedule', 'admin', true, true),
('coach-trip-schedule', 'coach', true, true),
('coach-trip-schedule', 'athlete', false, false),
('coach-trip-schedule', 'parent', false, false),
('scores', 'admin', true, true),
('scores', 'coach', true, true),
('scores', 'athlete', true, true),
('scores', 'parent', true, false),
('scores-stats', 'admin', true, true),
('scores-stats', 'coach', true, true),
('scores-stats', 'athlete', true, false),
('scores-stats', 'parent', true, false),
('community', 'admin', true, true),
('community', 'coach', true, true),
('community', 'athlete', true, false),
('community', 'parent', true, false),
('polls', 'admin', true, true),
('polls', 'coach', true, true),
('polls', 'athlete', true, true),
('polls', 'parent', true, true),
('consultations', 'admin', true, true),
('consultations', 'coach', true, true),
('consultations', 'athlete', true, true),
('consultations', 'parent', true, true),
('training-journal', 'admin', true, true),
('training-journal', 'coach', true, true),
('training-journal', 'athlete', true, true),
('training-journal', 'parent', true, false),
('attendance', 'admin', true, true),
('attendance', 'coach', true, true),
('attendance', 'athlete', true, true),
('attendance', 'parent', true, false),
('todo-list', 'admin', true, true),
('todo-list', 'coach', true, true),
('todo-list', 'athlete', true, true),
('todo-list', 'parent', false, false),
('course-management', 'admin', true, true),
('course-management', 'coach', true, true),
('course-management', 'athlete', false, false),
('course-management', 'parent', false, false),
('course-info', 'admin', true, true),
('course-info', 'coach', true, true),
('course-info', 'athlete', true, false),
('course-info', 'parent', true, false),
('reports', 'admin', true, true),
('reports', 'coach', true, true),
('reports', 'athlete', true, false),
('reports', 'parent', true, false),
('coach-selection', 'admin', true, true),
('coach-selection', 'coach', true, true),
('coach-selection', 'athlete', true, true),
('coach-selection', 'parent', true, false),
('statistics', 'admin', true, true),
('statistics', 'coach', true, true),
('statistics', 'athlete', false, false),
('statistics', 'parent', false, false),
('player-reports', 'admin', true, true),
('player-reports', 'coach', true, true),
('player-reports', 'athlete', false, false),
('player-reports', 'parent', false, false),
('assigned-athletes', 'admin', true, true),
('assigned-athletes', 'coach', true, true),
('assigned-athletes', 'athlete', false, false),
('assigned-athletes', 'parent', false, false),
('tournament-results', 'admin', true, true),
('tournament-results', 'coach', true, true),
('tournament-results', 'athlete', true, false),
('tournament-results', 'parent', true, false),
('lesson-list', 'admin', true, true),
('lesson-list', 'coach', true, true),
('lesson-list', 'athlete', false, false),
('lesson-list', 'parent', false, false),
('training-list', 'admin', true, true),
('training-list', 'coach', true, true),
('training-list', 'athlete', false, false),
('training-list', 'parent', false, false),
('challenge-list', 'admin', true, true),
('challenge-list', 'coach', true, true),
('challenge-list', 'athlete', false, false),
('challenge-list', 'parent', false, false),
('attendance-kiosk', 'admin', true, true),
('attendance-kiosk', 'coach', true, true),
('attendance-kiosk', 'athlete', true, true),
('attendance-kiosk', 'parent', true, false),
('branches', 'admin', true, true),
('branches', 'coach', true, false),
('branches', 'athlete', false, false),
('branches', 'parent', false, false),
('athletes', 'admin', true, true),
('athletes', 'coach', true, true),
('athletes', 'athlete', false, false),
('athletes', 'parent', false, false),
('coaches', 'admin', true, true),
('coaches', 'coach', false, false),
('coaches', 'athlete', false, false),
('coaches', 'parent', false, false),
('parents', 'admin', true, true),
('parents', 'coach', true, false),
('parents', 'athlete', false, false),
('parents', 'parent', false, false),
('permissions', 'admin', true, true),
('permissions', 'coach', false, false),
('permissions', 'athlete', false, false),
('permissions', 'parent', false, false),
('menu-management', 'admin', true, true),
('menu-management', 'coach', false, false),
('menu-management', 'athlete', false, false),
('menu-management', 'parent', false, false),
('temp-swing-skeleton', 'admin', true, true),
('temp-swing-skeleton', 'coach', true, true),
('temp-swing-skeleton', 'athlete', true, false),
('temp-swing-skeleton', 'parent', true, false),
('temp-swing-test', 'admin', true, true),
('temp-swing-test', 'coach', true, true),
('temp-swing-test', 'athlete', true, false),
('temp-swing-test', 'parent', true, false)
ON CONFLICT (menu_key, role) DO NOTHING;
